package com.example.librarypro.Navigation

const val ROUTE_DASHBOARD ="home"
const val ROUTE_SIGNUP ="signup"
const val ROUTE_GET_STARTED ="start"
const val ROUTE_LOGIN ="login"
const val ROUTE_RESET_PASSWORD ="reset pass"
const val ROUTE_FORGOT_PASSWORD ="forgot-pass"
const val ROUTE_ADD_BOOK ="AddBook"
const val ROUTE_VIEW_BOOK ="ViewBook"
const val ROUTE_UPDATE_BOOK ="UpdateBook"
const val ROUTE_USER ="UserScreen"
const val ROUTE_LIBRARIAN ="LibrarianScreen"
const val ROUTE_BORROWED_BOOKS="borrowedBook"
const val ROUTE_SEARCH_BOOK ="searchBook"
const val ROUTE_RETURN_BOOK ="return-book"
const val ROUTE_BORROW_BOOK ="borrow-book"
const val ROUTE_UPLOAD_BOOK ="Upload-book"
const val ROUTE_VIEW_UPLOAD ="view_upload"